### ISSUE TITLE
.obj files from Odyssey give error message when imported to Blender.

### ISSUE THREAD

**Issue by minermanb** [theawesomecoder61/Blacksmith#1]
The error is:
```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\io_scene_obj\__init__.py", line 148, in execute
    return import_obj.load(context, **keywords)
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\io_scene_obj\import_obj.py", line 1287, in load
    dataname,
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\io_scene_obj\import_obj.py", line 795, in create_mesh
    blen_uvs.data[lidx].uv = verts_tex[0 if (face_uvidx is ...) else face_uvidx]
IndexError: list index out of range

location: <unknown location>:-1


```

**Comment by theawesomecoder61** [comment]
1.7 will fix this. Thanks.
